# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1-ring-to-rule-them-@ll

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080